connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *connection
  database: date_learning_helper_development

test: &test
  <<: *connection
  database: date_learning_helper_test

production:
  <<: *default
  database: date_learning_helper_production
  username: date_learning_helper
  password: <%= ENV['DATE_LEARNING_HELPER_DATABASE_PASSWORD'] %>