#= require jquery
#= require jquery_ujs
#= require turbolinks
#= require bootstrap-sprockets
#= require_tree .
#= require_self
#= require bootbox
#= require timelineJS/embed
#=require timelineJS/locale/pl